cargo-features = ["edition"]

[package]
name = "rust"
version = "0.1.0"
authors = []
edition = '2018'

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.11"
serde_json = "1.0.20"
enum-primitive-derive = "0.1.2"
lazy_static = "1.0.1"
env_logger = "0.5.10"
log = "0.4.2"
itertools = "0.7.8"
strum = "0.9.0"
strum_macros = "0.9.0"
derive-new = "0.5.4"

[profile.dev]
panic = 'abort'

# to see the release binary in development (for size reasons mostly) uncomment
# these lines
# opt-level = 's'
# lto = true
# debug = false
# overflow-checks = false
# debug-assertions = false
# incremental = false

[profile.release]
opt-level = 's'
panic = 'abort'
lto = true
