[package]
name = "rust"
version = "0.1.0"
authors = []

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde_json = "1.0.17"
enum-primitive-derive = "0.1.2"
num-traits = "0.1.2"

[profile.dev]
panic = 'abort'

# to see the release binary in development (for size reasons mostly) uncomment
# these lines
# opt-level = 's'
# lto = true
# debug = false
# overflow-checks = false
# debug-assertions = false
# incremental = false

[profile.release]
opt-level = 's'
panic = 'abort'
lto = true
